//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: command_id.proto
namespace Cmd.ID
{
    [global::ProtoBuf.ProtoContract(Name=@"CMD")]
    public enum CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_INVALID", Value=0)]
      CMD_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_HEART_BEAT_REQ", Value=4096)]
      CMD_HEART_BEAT_REQ = 4096,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_HEART_BEAT_RSP", Value=4097)]
      CMD_HEART_BEAT_RSP = 4097,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_HEART_BEAT_RSP1", Value=16)]
      CMD_HEART_BEAT_RSP1 = 16
    }
  
}