//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: command_protocol_war.proto
namespace PROTOCOL_WAR
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_ENTER_GAME_REQ")]
  public partial class CMD_ENTER_GAME_REQ : global::ProtoBuf.IExtensible
  {
    public CMD_ENTER_GAME_REQ() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_ENTER_GAME_RSP")]
  public partial class CMD_ENTER_GAME_RSP : global::ProtoBuf.IExtensible
  {
    public CMD_ENTER_GAME_RSP() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_START_GAME_REQ")]
  public partial class CMD_START_GAME_REQ : global::ProtoBuf.IExtensible
  {
    public CMD_START_GAME_REQ() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_START_GAME_RSP")]
  public partial class CMD_START_GAME_RSP : global::ProtoBuf.IExtensible
  {
    public CMD_START_GAME_RSP() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_WAR_MOVE_REQ")]
  public partial class CMD_WAR_MOVE_REQ : global::ProtoBuf.IExtensible
  {
    public CMD_WAR_MOVE_REQ() {}
    
    private bool _is_down = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"is_down", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_down
    {
      get { return _is_down; }
      set { _is_down = value; }
    }
    private int _degree = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"degree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int degree
    {
      get { return _degree; }
      set { _degree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_WAR_MOVE_RSP")]
  public partial class CMD_WAR_MOVE_RSP : global::ProtoBuf.IExtensible
  {
    public CMD_WAR_MOVE_RSP() {}
    
    private int _seat = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private bool _is_down = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"is_down", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_down
    {
      get { return _is_down; }
      set { _is_down = value; }
    }
    private int _degree = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"degree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int degree
    {
      get { return _degree; }
      set { _degree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_WAR_COMMAND_NOTICE")]
  public partial class CMD_WAR_COMMAND_NOTICE : global::ProtoBuf.IExtensible
  {
    public CMD_WAR_COMMAND_NOTICE() {}
    
    private int _sequence = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }
    private byte[] _commands = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"commands", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] commands
    {
      get { return _commands; }
      set { _commands = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}