//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: command_id.proto
namespace Cmd.ID
{
    [global::ProtoBuf.ProtoContract(Name=@"CMD")]
    public enum CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_INVALID", Value=0)]
      CMD_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_HEART_BEAT_REQ", Value=1000)]
      CMD_HEART_BEAT_REQ = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_HEART_BEAT_RSP", Value=1001)]
      CMD_HEART_BEAT_RSP = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_CREATE_ROOM_REQ", Value=1002)]
      CMD_CREATE_ROOM_REQ = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_CREATE_ROOM_RSP", Value=1003)]
      CMD_CREATE_ROOM_RSP = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_LEAVE_ROOM_REQ", Value=1004)]
      CMD_LEAVE_ROOM_REQ = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_LEAVE_ROOM_RSP", Value=1005)]
      CMD_LEAVE_ROOM_RSP = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_LEAVE_ROOM_NOTICE", Value=1006)]
      CMD_LEAVE_ROOM_NOTICE = 1006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_ROOM_LIST_REQ", Value=1007)]
      CMD_ROOM_LIST_REQ = 1007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_ROOM_LIST_RSP", Value=1008)]
      CMD_ROOM_LIST_RSP = 1008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_ENTER_GAME_REQ", Value=1009)]
      CMD_ENTER_GAME_REQ = 1009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_ENTER_GAME_RSP", Value=1010)]
      CMD_ENTER_GAME_RSP = 1010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_START_GAME_REQ", Value=1011)]
      CMD_START_GAME_REQ = 1011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_START_GAME_RSP", Value=1012)]
      CMD_START_GAME_RSP = 1012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_WAR_MOVE_REQ", Value=1013)]
      CMD_WAR_MOVE_REQ = 1013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_WAR_MOVE_RSP", Value=1014)]
      CMD_WAR_MOVE_RSP = 1014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_WAR_COMMAND_NOTICE", Value=1015)]
      CMD_WAR_COMMAND_NOTICE = 1015
    }
  
}