# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c_table_Avatar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_table_pb2 as common__table__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='c_table_Avatar.proto',
  package='Table',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x63_table_Avatar.proto\x12\x05Table\x1a\x12\x63ommon_table.proto\"q\n\x06\x41VATAR\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x32\n\tbody_type\x18\x03 \x01(\x0e\x32\x0f.Table.BodyType:\x0e\x42ODY_TYPE_NONE\x12\x19\n\x04\x61\x61\x62\x62\x18\x04 \x01(\x0b\x32\x0b.Table.AABB\"+\n\x0c\x41VATAR_ARRAY\x12\x1b\n\x04rows\x18\x01 \x03(\x0b\x32\r.Table.AVATAR'
  ,
  dependencies=[common__table__pb2.DESCRIPTOR,])




_AVATAR = _descriptor.Descriptor(
  name='AVATAR',
  full_name='Table.AVATAR',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Table.AVATAR.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Table.AVATAR.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body_type', full_name='Table.AVATAR.body_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aabb', full_name='Table.AVATAR.aabb', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=164,
)


_AVATAR_ARRAY = _descriptor.Descriptor(
  name='AVATAR_ARRAY',
  full_name='Table.AVATAR_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='Table.AVATAR_ARRAY.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=209,
)

_AVATAR.fields_by_name['body_type'].enum_type = common__table__pb2._BODYTYPE
_AVATAR.fields_by_name['aabb'].message_type = common__table__pb2._AABB
_AVATAR_ARRAY.fields_by_name['rows'].message_type = _AVATAR
DESCRIPTOR.message_types_by_name['AVATAR'] = _AVATAR
DESCRIPTOR.message_types_by_name['AVATAR_ARRAY'] = _AVATAR_ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AVATAR = _reflection.GeneratedProtocolMessageType('AVATAR', (_message.Message,), {
  'DESCRIPTOR' : _AVATAR,
  '__module__' : 'c_table_Avatar_pb2'
  # @@protoc_insertion_point(class_scope:Table.AVATAR)
  })
_sym_db.RegisterMessage(AVATAR)

AVATAR_ARRAY = _reflection.GeneratedProtocolMessageType('AVATAR_ARRAY', (_message.Message,), {
  'DESCRIPTOR' : _AVATAR_ARRAY,
  '__module__' : 'c_table_Avatar_pb2'
  # @@protoc_insertion_point(class_scope:Table.AVATAR_ARRAY)
  })
_sym_db.RegisterMessage(AVATAR_ARRAY)


# @@protoc_insertion_point(module_scope)
